import type { Metadata } from "next";
import MainLayout from "@/components/layouts/main-layout";
import { Roboto } from "next/font/google";
import "./globals.css";

import Providers from "@/components/providers/providers";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "my next js application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning={false}
      className="light"
      style={{ colorScheme: "light" }}
    >
      <body className={`${roboto.className} flex flex-col min-h-screen`}>
        <Providers>
          <MainLayout>{children}</MainLayout>
        </Providers>
      </body>
    </html>
  );
}
